site:
  title: aisradar_pi Manual
  url:  https://nowhere.net
  start_page: ais_radar_display:ROOT:ais_radar_display.adoc
content:
  sources:
    - url: ../..
      start_path: manual/ais_radar_display/
      branches: HEAD
      edit_url: true
ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true
output:
  dir: ./docs
  clean: true              
